services:
  # --- MongoDB ---
  mongodb:
    image: mongo:latest
    container_name: mongodb
    mem_limit: 512m
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - microservices-network

  # --- Service Discovery ---
  eureka:
    build: ./spring-eureka-server
    container_name: eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-network

  # --- Message Broker Stack ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    mem_limit: 512m
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    mem_limit: 1024m
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "19092:19092"
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # --- Stream Producer ---
  stream-producer:
    build: ./stream-producer
    container_name: stream-producer
    mem_limit: 512m
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      kafka:
        condition: service_healthy
      eureka:
        condition: service_started
    restart: on-failure
    networks:
      - microservices-network

  # --- Stream Consumer ---
  stream-consumer:
    build: ./stream-consumer
    container_name: stream-consumer
    mem_limit: 512m
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/db
    depends_on:
      kafka:
        condition: service_healthy
      eureka:
        condition: service_started
      mongodb:
        condition: service_started
    restart: on-failure
    networks:
      - microservices-network

  # -- Gateway ---
  gateway:
    build: ./gw
    container_name: api-gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_GATEWAY_ROUTES[0].ID=json-placeholder
      - SPRING_CLOUD_GATEWAY_ROUTES[0].URI=https://jsonplaceholder.typicode.com
      - SPRING_CLOUD_GATEWAY_ROUTES[0].PREDICATES[0]=Path=/comments/**
      - SPRING_CLOUD_GATEWAY_ROUTES[0].PREDICATES[1]=Method=GET
      - SPRING_CLOUD_GATEWAY_ROUTES[1].ID=http-service
      - SPRING_CLOUD_GATEWAY_ROUTES[1].URI=lb://HTTP
      - SPRING_CLOUD_GATEWAY_ROUTES[1].PREDICATES[0]=Path=/http/**
      - SPRING_CLOUD_GATEWAY_ROUTES[1].PREDICATES[1]=Method=GET
      - SPRING_CLOUD_GATEWAY_ROUTES[1].FILTERS[0]=StripPrefix=1
    depends_on:
      eureka:
        condition: service_started
    restart: on-failure
    networks:
      - microservices-network
  # --- http hello world ---
  http:
    build: ./hello-world
    container_name: http
    mem_limit: 512m
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - gateway
    networks:
      - microservices-network
    restart: on-failure


networks:
  microservices-network:
    driver: bridge