services:
  # --- Service Discovery ---
  eureka:

    build: ./spring-eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Message Broker Stack ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    mem_limit: 512m
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  # --- Your Custom Applications ---
  stream-producer:
    build: ./stream-producer
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,kafka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      eureka:
        condition: service_healthy
      kafka:
        condition: service_started

  stream-consumer:
    build: ./stream-consumer
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,kafka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      eureka:
        condition: service_healthy
      kafka:
        condition: service_started